admin/views.py
from flask import Blueprint, render_template, flash

from model import db
from admin.forms import TagForm
from auth.authentication import login_required, current_user
from tags.models import Tag

app = Blueprint('admin', __name__, url_prefix='/admin')


@app.before_request
@login_required
def before_request():
    """Ensure all endpoints are authenticated"""
    if not current_user.admin:
        return "Not authorised", 403


@app.route('/', methods=['GET', 'POST'])
def view():
    form = TagForm()
    if form.validate_on_submit():
        t = Tag()
        t.name = form.name.data
        t.enabled = True
        db.session.add(t)
        db.session.commit()
        flash("Created tag", 'success')

    return render_template('admin/index.html', form=form)

issue/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request

from auth.authentication import login_required, current_user
from issue import models
from issue.forms import IssueForm
from model import db

app = Blueprint('issue', __name__, url_prefix='/issue')


@app.before_request
@login_required
def before_request():
    """Ensure all endpoints are authenticated"""


@app.route('/')
def overview():
    """View all issues"""
    issues = models.Issue.query.order_by(models.Issue.updated.desc())

    return render_template('issue/overview.html', issues=issues)


@app.route('/new', methods=['GET', 'POST'])
def create():
    form = IssueForm()

    if form.validate_on_submit():
        db.session.autoflush = False
        issue = models.Issue()
        form.populate_obj(issue)
        db.session.add(issue)
        db.session.commit()
        return redirect(url_for('issue.view', issue=issue.id))

    return render_template('issue/new.html', form=form)


@app.route('/<int:issue>', methods=['GET', 'POST'])
def view(issue: int):
    """View a specific issue"""

    issue = db.session.query(models.Issue).get_or_404(issue)

    form = IssueForm(obj=issue)
    if form.validate_on_submit():
        db.session.autoflush = False
        form.populate_obj(issue)
        db.session.add(issue)
        db.session.commit()

    return render_template('issue/view.html', issue=issue, statuses=models.Status.get_ordered(), form=form)


@app.route('/search')
def search():
    return 'Not Implemented'

tags/views.py
from flask import Blueprint, redirect, url_for, render_template

from auth.authentication import login_required
from tags.models import Tag

app = Blueprint('tag', __name__, url_prefix='/tag')


@app.before_request
@login_required
def before_request():
    """Ensure all endpoints are authenticated"""


@app.route('/')
def overview():
    return render_template('tags/overview.html', tags=Tag.query)


@app.route('/<int:tag>')
def view(tag: int):
    """View a specific tag"""
    return 'Not Implemented'


@app.route('/name/<string:name>')
def view_name(name: str):
    tag = Tag.query.filter(Tag.name.ilike(name)).first_or_404()
    return redirect(url_for('tag.view', tag=tag.id))

user/views.py
from flask import Blueprint, render_template, flash

from auth.authentication import login_required, current_user
from issue.models import Issue
from model import db
from user.forms import EditUserForm
from user.models import User

app = Blueprint('user', __name__, url_prefix='/user')


@app.before_request
@login_required
def before_request():
    """Ensure all endpoints are authenticated"""


@app.route('/edit', methods=['GET', 'POST'])
def edit_user():
    form = EditUserForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        db.session.add(current_user)
        db.session.commit()
        flash("Updated Details", 'success')

    return render_template('user/edit.html', form=form)


@app.route('/<int:user>')
def view(user: int):
    user = User.query.get_or_404(user)

    return render_template('user/issues.html', user=user, issues=Issue.get_assigned(user, show_closed=True))

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>{% if title %}{{ title }} - {% endif %}RepairTracker</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.3/dist/semantic.min.css">
  {% block head %}{% endblock %}
  <style type="text/css">
  html {
      font-size: 12px;
  }
  body {
    background-color: #FFFFFF;
  }
  .ui.menu .item img.logo {
    margin-right: 1.5em;
  }

  .ui.header .category.label {
      margin-left: 0;
      margin-bottom: 4px;
  }

  .ui.search .results .content {
      padding: 0 !important;
  }

  .ui.search .results .content .title {
      margin: -.14285714em 0 0 !important;;
      font-family: Lato, 'Helvetica Neue', Arial, Helvetica, sans-serif !important;;
      font-weight: 700 !important;;
      font-size: 1em !important;;
      color: rgba(0, 0, 0, .85) !important;
      padding: .5em 0 !important;
      border: none !important;
  }


  .main.container {
    margin-top: 5em;
  }
  .wireframe {
    margin-top: 2em;
  }
  .ui.footer.segment {
    margin: 5em 0em 0em;
    padding: 5em 0em;
  }
  .issue.closed {
      text-decoration: line-through;
  }
  </style>
</head>
<body>
  <div class="ui fixed inverted menu">
    <div class="ui container">
      <a href="{{ url_for('dashboard.index') }}" class="header item">
          <span class="logo">
              <i class="wrench icon"></i>
          </span>
        RepairTracker
      </a>
      <a href="{{ url_for('dashboard.index') }}" class="item">Home</a>
      <a href="{{ url_for('issue.overview') }}" class="item">Issues</a>
      <a href="{{ url_for('category.overview') }}" class="item">Categories</a>
      <a href="{{ url_for('tag.overview') }}" class="item">Tags</a>
      {% if current_user.admin %}
          <a href="{{ url_for('admin.view') }}" class="item">Admin</a>
      {% endif %}
      <div class="right item">
          <form class="ui action input search" id="header_search">
            <div class="ui icon input">
                <input class="prompt" value="" type="text" placeholder="Search...">
                <i class="search icon"></i>
            </div>
            <div class="results"></div>
          </form>
      </div>
        <div class="item">
            <a class="ui labeled icon primary button" href="{{ url_for('issue.create') }}">
                <i class="plus icon"></i>
                New Issue
            </a>
        </div>

        <div class="item">
            <a href="{{ url_for('user.edit_user') }}">
                <i class="icon user circle"></i>
                {{ current_user.name }}
            </a>
        </div>
    </div>
  </div>

  <div class="ui main container">
      {% with errors = get_flashed_messages(category_filter=["error"]) %}
        {% if errors %}
            <div class="ui negative message">{%- for msg in errors %}{{ msg }}{% endfor -%}</div>
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
  </div>

  <div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
        &copy; 2019 Repair Tracker
    </div>
  </div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.3/dist/semantic.min.js"></script>
<script>
$(document).ready(function() {
    $('.ui.dropdown:not(.ignore)').dropdown();
    $('.ui.accordion').accordion();
    $('.ui.modal').modal();


    $("#header_search").search({
        apiSettings: {
            url: "/api/1/issue/search?query={query}"
        },
        minCharacters: 2,
        showNoResults: true,
        onSelect: function(result) {
            if (result) {
                window.location = '/issue/' + result.id;
            }
        }
    }).search('set value', '');
});
</script>
{% block script %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1 class="ui header">Dashboard</h1>
    <div class="ui grid">
        <div class="ui eight wide column">
            <div class="ui segment">
                <h2 class="ui header">Unassigned Issues</h2>
                <table class="ui celled table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Modified</th>
                            <th>Age</th>
                        </tr>
                    </thead>
                    {% for issue in unassigned_issues %}
                    <tr>
                        <td><a href="{{ url_for('issue.view', issue=issue.id) }}">{{ issue | renderissue | safe }}</a></td>
                        <td>{{ issue.updated | datetime }}</td>
                        <td>{{ issue.age }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="ui eight wide column">
            <div class="ui segment">
                <h2 class="ui header">Assigned To Me</h2>
                <table class="ui celled table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Modified</th>
                            <th>Age</th>
                        </tr>
                    </thead>
                    {% for issue in assigned_issues %}
                    <tr>
                        <td><a href="{{ url_for('issue.view', issue=issue.id) }}">{{ issue | renderissue | safe }}</a></td>
                        <td>{{ issue.updated | datetime }}</td>
                        <td>{{ issue.age }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="ui grid">
        <div class="ui eight wide column">
            <div class="ui segment">
                <h2 class="ui header">Reported By Me</h2>
                <table class="ui celled table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Modified</th>
                            <th>Age</th>
                        </tr>
                    </thead>
                    {% for issue in reported_issues %}
                    <tr>
                        <td><a href="{{ url_for('issue.view', issue=issue.id) }}">{{ issue | renderissue | safe }}</a></td>
                        <td>{{ issue.updated | datetime }}</td>
                        <td>{{ issue.age }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="ui eight wide column">
            <div class="ui segment">
                <h2 class="ui header">Oldest Open Issues</h2>
                <table class="ui celled table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Modified</th>
                            <th>Age</th>
                        </tr>
                    </thead>
                    {% for issue in oldest_opened %}
                    <tr>
                        <td><a href="{{ url_for('issue.view', issue=issue.id) }}">{{ issue | renderissue | safe }}</a></td>
                        <td>{{ issue.updated | datetime }}</td>
                        <td>{{ issue.age }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}